### ISSUE TITLE
Missing pip deps in docker image

### ISSUE THREAD

**Issue by binitshah** [mko-x/fork-scan#1]
Hello, I'd like to try your project, however, upon running the `docker run -p 8081:80 mk0x/docker-fork-scan` command, I get:

```
INFO gave up: uwsgi entered FATAL state, too many start retries too quickly
```

It seems that the docker image is missing `requests`, `BeautifulSoup.bs4`, and other pip dependencies.

**Comment by mko-x** [comment]
This project is no longer maintained.
